//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDC.Generator.Kamelon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDC.Generator.Kamelon.Resources.LibraryResource", typeof(LibraryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using LDC.Model.Dto.EntityDtos.$;
        ///using LDC.Model.Entity.$;
        ///
        ///namespace ||namespace||
        ///{
        ///	public static class $Extensions
        ///	{
        ///		public static $ ToEntity(this $Dto dto, $ entityToAssign = null)
        ///		{
        ///			var entity = entityToAssign ?? new $().AssignBAseValuesToEntity(dto);
        ///			
        ///			{ToEntity}
        ///			
        ///			return entity;
        ///		}
        ///		
        ///		public static $Dto ToDto(this $ entity)
        ///		{
        ///			var dto = new $Dto().AssignBAseValuesToEntity(entity);
        ///			
        ///			{ToDto}
        ///			
        ///			return dto;
        ///		}
        ///	}
        ///}.
        /// </summary>
        public static string DataExtension {
            get {
                return ResourceManager.GetString("DataExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///{test}
        ///namespace ||namespace||
        ///{
        ///	public class $Dto : EntityBaseDto&lt;long&gt;
        ///	{
        ///		{0}
        ///	}
        ///}.
        /// </summary>
        public static string Dto {
            get {
                return ResourceManager.GetString("Dto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using LDC.Model.Entity.$;
        ///
        ///namespace ||namespace||
        ///{
        ///	public class $Map : EntityMap&lt;$&gt;
        ///	{
        ///		public $Map()
        ///		{
        ///			Table(&quot;$s&quot;);
        ///			{Maps}
        ///		}	
        ///	}
        ///}.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using LDC.Assemblies.Repository.BasicAssemblies;
        ///using LDC.Model.Entity.$;
        ///
        ///namespace ||namespace||
        ///{
        ///	public interface I$Repository : IRepository&lt;$&gt;
        ///	{
        ///
        ///	}
        ///
        ///	public class $Repository : RepositoryBase&lt;$&gt;, I$Repository
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using LDC.Assemblies.Process.ProcessResult;
        ///using LDC.Assemblies.Service.BasicAssemblies;
        ///using LDC.Assemblies.Service._authorization;
        ///using LDC.Model.Dto.EntityDtos.$;
        ///
        ///namespace ||namespace||
        ///{
        ///    public interface I$Service : IService
        ///    {
        ///        [ServiceAuthorization(ServiceOperationType.Save, Description = &quot;&quot;)]
        ///        DataResult&lt;long&gt; Save($Dto dto);
        ///		
        ///        [ServiceAuthorization(ServiceOperationType.Update, Description = &quot;&quot;)]
        ///        DataResult&lt;boo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
    }
}
